<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-25T17:53:01Z" name="Default suite" finished-at="2023-04-25T17:53:39Z" duration-ms="37355">
    <groups>
    </groups>
    <test started-at="2023-04-25T17:53:01Z" name="Default test" finished-at="2023-04-25T17:53:39Z" duration-ms="37355">
      <class name="MyTestCases.BloggingSiteTesting">
        <test-method is-config="true" signature="setup()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:01Z" name="setup" finished-at="2023-04-25T17:53:03Z" duration-ms="1170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TestCase1()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:03Z" name="TestCase1" finished-at="2023-04-25T17:53:05Z" duration-ms="2574" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method signature="TestCase2()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:05Z" name="TestCase2" finished-at="2023-04-25T17:53:07Z" duration-ms="2206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
        <test-method signature="TestCase3()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:07Z" name="TestCase3" finished-at="2023-04-25T17:53:27Z" duration-ms="20126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method signature="TestCase4()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:27Z" name="TestCase4" finished-at="2023-04-25T17:53:37Z" duration-ms="9353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase4 -->
        <test-method signature="TestCase5()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:37Z" name="TestCase5" finished-at="2023-04-25T17:53:38Z" duration-ms="1416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost:8080/logout] but found [http://localhost:3000/account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/logout] but found [http://localhost:3000/account]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at MyPageObjects.createTest.logout(createTest.java:145)
at MyTestCases.BloggingSiteTesting.TestCase5(BloggingSiteTesting.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase5 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:MyTestCases.BloggingSiteTesting@7d94beb9]" started-at="2023-04-25T17:53:38Z" name="teardown" finished-at="2023-04-25T17:53:39Z" duration-ms="488" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- MyTestCases.BloggingSiteTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
